LoginBiblioteca/Models/Borrow.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Borrow
    {
        public int Id_imprumut { get; set; }
        public string Id_user { get; set; }
        public Nullable<int> Id_carte { get; set; }
        public string Date { get; set; }

        [Required]
        [Range(1, 5, ErrorMessage = "Introdu un numar valid")]
        public string Nr_carti { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Carti Carti { get; set; }
    }
}

LoginBiblioteca/Controllers/BorrowsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LoginBiblioteca.Models;

namespace LoginBiblioteca.Controllers
{
    [Authorize]
    public class BorrowsController : Controller
    {
        private BooksDBEnities db = new BooksDBEnities();

        // GET: Borrows
        public ActionResult Index()
        {
            var borrows = db.Borrows.Include(b => b.AspNetUser).Include(b => b.Carti).Where(b => b.AspNetUser.Email == User.Identity.Name);
            return View(borrows.ToList());
        }

        // GET: Borrows/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrow borrow = db.Borrows.Find(id);
            if (borrow == null)
            {
                return HttpNotFound();
            }
            return View(borrow);
        }

        // GET: Borrows/Create
        public ActionResult Create()
        {
            ViewBag.Id_user = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Id_carte = new SelectList(db.Cartis, "Id", "Nume_carte");
            
            return View();
        }

        // POST: Borrows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_imprumut,Id_user,Id_carte,Date,Nr_carti")] Borrow borrow)
        {
            if (ModelState.IsValid)
            {
                borrow.Date = DateTime.Today.ToString();
                var us = db.Database.SqlQuery<string>("SELECT Id FROM AspNetUsers WHERE Email = @p0", User.Identity.Name).ToArray();
                borrow.Id_user = us[0];
                db.Borrows.Add(borrow);                
                db.Database.ExecuteSqlCommand("UPDATE Carti SET Nr_Disponibil=Nr_Disponibil-@p0 WHERE Id=@p1", borrow.Nr_carti, borrow.Id_carte);
                db.SaveChanges();                
                //db.Database.ExecuteSqlCommand(cmd);
                return RedirectToAction("Index");
            }

            ViewBag.Id_user = new SelectList(db.AspNetUsers, "Id", "Email", borrow.Id_user);
            ViewBag.Id_carte = new SelectList(db.Cartis, "Id", "Nume_carte", borrow.Id_carte);
            return View(borrow);
        }

        // GET: Borrows/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrow borrow = db.Borrows.Find(id);
            if (borrow == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_user = new SelectList(db.AspNetUsers, "Id", "Email", borrow.Id_user);
            ViewBag.Id_carte = new SelectList(db.Cartis, "Id", "Nume_carte", borrow.Id_carte);
            return View(borrow);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_imprumut,Id_user,Id_carte,Date,Nr_carti")] Borrow borrow)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrow).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_user = new SelectList(db.AspNetUsers, "Id", "Email", borrow.Id_user);
            ViewBag.Id_carte = new SelectList(db.Cartis, "Id", "Nume_carte", borrow.Id_carte);
            return View(borrow);
        }

        // GET: Borrows/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrow borrow = db.Borrows.Find(id);
            if (borrow == null)
            {
                return HttpNotFound();
            }
            return View(borrow);
        }

        // POST: Borrows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Borrow borrow = db.Borrows.Find(id);
            db.Database.ExecuteSqlCommand("UPDATE Carti SET Nr_Disponibil=Nr_Disponibil+@p0 WHERE Id=@p1", borrow.Nr_carti, borrow.Id_carte);
            db.Borrows.Remove(borrow); 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LoginBiblioteca/Views/Borrows/Create.cshtml
@model LoginBiblioteca.Models.Borrow

@{
    ViewBag.Title = "Imprumuta";
}

<h2>Imprumuta carte</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Imprumuta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Id_carte, "Carte", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_carte", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_carte, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nr_carti,"Nr carti", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nr_carti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nr_carti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Imprumuta" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Inapoi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginBiblioteca/Views/Borrows/Delete.cshtml
@model LoginBiblioteca.Models.Borrow

@{
    ViewBag.Title = "Delete";
}


<h3>Returnezi?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Data
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
           Nr Carti
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_carti)
        </dd>

        <dt>
            Numele cartii
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carti.Nume_carte)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Returneaza" class="btn btn-success" /> |
            @Html.ActionLink("Inapoi", "Index")
        </div>
    }
</div>

LoginBiblioteca/Views/Borrows/Details.cshtml
@model LoginBiblioteca.Models.Borrow

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Borrow</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nr_carti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_carti)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carti.Nume_carte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carti.Nume_carte)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_imprumut }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LoginBiblioteca/Views/Borrows/Edit.cshtml
@model LoginBiblioteca.Models.Borrow

@{
    ViewBag.Title = "Edit";
}

<h2>Editare</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id_imprumut)
    @Html.HiddenFor(model => model.Id_user)
    @Html.HiddenFor(model => model.Id_carte)
    @Html.HiddenFor(model => model.Date)


    @*<div class="form-group">
        @Html.LabelFor(model => model.Id_user, "Id_user", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_user", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_user, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_carte, "Id_carte", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_carte", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_carte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Nr_carti, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nr_carti, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nr_carti, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salveaza" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Inapoi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginBiblioteca/Views/Borrows/Index.cshtml
@model IEnumerable<LoginBiblioteca.Models.Borrow>

@{
    ViewBag.Title = "Imprumut";
}

<h2>Sumar</h2>

<p>
    @Html.ActionLink("Imprumut nou", "Create","Borrows", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            Data Imprumutului
        </th>
        <th>
            Nr carti
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th>
            Nume Carte
        </th>
        <th>
            Optiuni
        </th>
    </tr>

@foreach (var item in Model)
{

    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nr_carti)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Carti.Nume_carte)
        </td>
        <td>
            @Html.ActionLink("Editeaza", "Edit", new { id = item.Id_imprumut }) |
            @Html.ActionLink("Returneaza", "Delete", new { id = item.Id_imprumut })
        </td>
    </tr>
       
}

</table>