LoginBiblioteca/Models/Carti.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carti()
        {
            this.Borrows = new HashSet<Borrow>();
        }
    
        public int Id { get; set; }
        public string Nume_carte { get; set; }
        public string Autor { get; set; }
        public string Editura { get; set; }
        public Nullable<int> Nr_Total { get; set; }
        public Nullable<int> Nr_Disponibil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrow> Borrows { get; set; }
    }
}

LoginBiblioteca/Controllers/CartiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LoginBiblioteca.Models;

namespace LoginBiblioteca.Controllers
{
    [Authorize(Users = "admin@admin.com")]
    public class CartiController : Controller
    {
        private BooksDBEnities db = new BooksDBEnities();

        // GET: Carti
        public ActionResult Index()
        {
            return View(db.Cartis.ToList());
        }

        public ActionResult List()
        {
            return View(db.Borrows.ToList());
        }
        // GET: Carti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carti carti = db.Cartis.Find(id);
            if (carti == null)
            {
                return HttpNotFound();
            }
            return View(carti);
        }

        // GET: Carti/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carti/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nume_carte,Autor,Editura,Nr_Total,Nr_Disponibil")] Carti carti)
        {
            if (ModelState.IsValid)
            {
                db.Cartis.Add(carti);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(carti);
        }

        // GET: Carti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carti carti = db.Cartis.Find(id);
            if (carti == null)
            {
                return HttpNotFound();
            }
            return View(carti);
        }

        // POST: Carti/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nume_carte,Autor,Editura,Nr_Total,Nr_Disponibil")] Carti carti)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carti).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carti);
        }

        // GET: Carti/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carti carti = db.Cartis.Find(id);
            if (carti == null)
            {
                return HttpNotFound();
            }
            return View(carti);
        }

        // POST: Carti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Carti carti = db.Cartis.Find(id);
            db.Cartis.Remove(carti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LoginBiblioteca/Views/Carti/Create.cshtml
@model LoginBiblioteca.Models.Carti

@{
    ViewBag.Title = "Adaugare";
}

<h2>Adaugare</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nume_carte,"Nume carte", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume_carte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume_carte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nr_Total,"Nr Total", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nr_Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nr_Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nr_Disponibil,"Nr disponibil", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nr_Disponibil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nr_Disponibil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Creeaza" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Inapoi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginBiblioteca/Views/Carti/Delete.cshtml
@model LoginBiblioteca.Models.Carti

@{
    ViewBag.Title = "Delete";
}

<div>
    <h4>Stergere</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nume carte:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume_carte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Editura):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Editura)
        </dd>

        <dt>
            Nr total:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_Total)
        </dd>

        <dt>
            Nr Disponibil:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_Disponibil)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sterge" class="btn btn-danger" /> |
            @Html.ActionLink("Inapoi", "Index")
        </div>
    }
</div>

LoginBiblioteca/Views/Carti/Details.cshtml
@model LoginBiblioteca.Models.Carti

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Carti</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nume_carte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume_carte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Editura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Editura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nr_Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nr_Disponibil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_Disponibil)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LoginBiblioteca/Views/Carti/Edit.cshtml
@model LoginBiblioteca.Models.Carti

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nume_carte, "Nume carte", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume_carte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume_carte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nr_Total, "Nr Total", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nr_Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nr_Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nr_Disponibil, "Nr Disponibil", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nr_Disponibil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nr_Disponibil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salveaza" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Inapoi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginBiblioteca/Views/Carti/Index.cshtml
@model IEnumerable<LoginBiblioteca.Models.Carti>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Adauga o noua intrare", "Create","Carti", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            Nume Carte
        </th>
        <th>
            Autor
        </th>
        <th>
            Editura
        </th>
        <th>
            Nr Total
        </th>
        <th>
            Nr Disponibil
        </th>
        <th>
            Optiuni
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nume_carte)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Editura)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nr_Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nr_Disponibil)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Sterge", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

LoginBiblioteca/Views/Carti/List.cshtml
@model IEnumerable<LoginBiblioteca.Models.Borrow>
<h3>Sumar imprumuturi</h3>
<hr/>
<table class="table">
    <tr>
        <th>
            Date
        </th>
        <th>
            Nr. carti
        </th>
        <th>
           Email
        </th>
        <th>
           Nume carte
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nr_carti)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Carti.Nume_carte)
        </td>
    </tr>
}

</table>